# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6666e24c7f6cb9d9a31a3828e4469c13a393c6d05f340045fe4c0a38737a8fd64376ddd4ad6686d3aadff6849678ef2d7aede9f3539b7df5dcd0f74df91d8ab

test:
  secret_key_base: a58eaa895dc8ef2b1ada3936b68fbbe623149d323bd955e49abb1467d4f525317c8cc5a45c8cfbbc86ac309e184808b7cf2c011c1a68cc7a7ec6bc47bcae3678

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
